[package]
name = "asgard"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "time"] }
httparse = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
